---
- name: Add apt-key (keyserver)
  apt_key: 
    id: "{{ marathon_apt_key_id }}"
    keyserver: "{{ marathon_apt_key_server }}"
    state: present
  when:
    - marathon_apt_key_id and marathon_apt_key_server
    - marathon_apt_key_url is not defined

- name: Add apt-key (url)
  apt_key: 
    id: "{{ marathon_apt_key_id }}"
    url: "{{ marathon_apt_key_url }}"
    state: present
  when:
    - marathon_apt_key_id and marathon_apt_key_url
    - marathon_apt_key_url is defined

- name: Add Mesosphere repo
  apt_repository: repo='deb {{ marathon_apt_url }} {{ ansible_distribution_release | lower }} main' state=present update_cache=yes

- name: Pin Marathon version
  template:
    src: marathon.pref.j2
    dest: /etc/apt/preferences.d/marathon.pref
  when: marathon_apt_pin_priority | default(false) | bool

- name: Install Marathon package
  apt: pkg={{ marathon_apt_package }} state=present
  notify: Restart marathon
